# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LockWhisper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LockWhisper
	pod 'ObjectivePGP'

  target 'LockWhisperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LockWhisperUITests' do
    # Pods for testing
  end

end
